[package]
name = "file-search"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
authors = ["Nordine Bittich"]
description = "File indexing and search"
repository = "https://github.com/nbittich/file-search"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.20", features = ["headers", "tracing"] }
axum-extra = "0.7.7"
calamine = { version = "0.21.2", features = ["chrono", "dates"] }
chrono = "0.4.26"
csv = "1.2.2"
serde = { version = "1.0.182", features = ["derive"] }
serde_json = "1.0.104"
tantivy = "0.20.2"
tokio = { version = "1.29.1", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
uuid = { version = "1.4.1", features = ["v4"] }
tower = "0.4.13"
tower-http = { version = "0.4.3", features = ["fs", "trace", "redirect"] }

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.0.7"
# The preferred Rust toolchain to use in CI (rustup toolchain syntax)
rust-toolchain-version = "1.71.1"
# CI backends to support (see 'cargo dist generate-ci')
ci = ["github"]
installers = ["shell"]
# The installers to generate for each app
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu"]
